// Copies the shared core (and the developer's local supabase-config.js) into
// renderer/vendor/ so the packaged app is self-contained and the renderer can
// reference everything with plain relative paths (no ../../ escaping the app root).
// Runs automatically before `npm start` and `npm run dist`.
'use strict';
const fs = require('fs');
const path = require('path');

const repoRoot = path.join(__dirname, '..');
const vendor = path.join(__dirname, 'renderer', 'vendor');
fs.mkdirSync(vendor, { recursive: true });

const shared = ['constants.js', 'db.js', 'core.js', 'insights.js'];
for (const f of shared) {
  fs.copyFileSync(path.join(repoRoot, 'shared', f), path.join(vendor, f));
}

// supabase-config.js is gitignored — copy the dev's local copy if present.
const cfg = path.join(repoRoot, 'supabase-config.js');
if (fs.existsSync(cfg)) {
  fs.copyFileSync(cfg, path.join(vendor, 'supabase-config.js'));
} else {
  // Write a stub so the renderer loads in local-only mode without erroring.
  fs.writeFileSync(
    path.join(vendor, 'supabase-config.js'),
    '// No supabase-config.js found at build time — cloud sync disabled (local-only mode).\n' +
    'window.SUPABASE_CONFIG = window.SUPABASE_CONFIG || null;\n'
  );
}

// Three.js as a plain global script. Three no longer publishes a UMD build,
// and ES modules can't be loaded over file:// in Electron (CORS blocks them),
// so wrap the self-contained CommonJS build (verified: zero require() calls)
// in an IIFE that hands the exports object to window.THREE.
const threeSrc = path.join(__dirname, 'node_modules', 'three', 'build', 'three.cjs');
if (fs.existsSync(threeSrc)) {
  const cjs = fs.readFileSync(threeSrc, 'utf8');
  fs.writeFileSync(path.join(vendor, 'three.js'),
    '// Generated by copy-shared.js — do not edit. Three.js CJS build wrapped as a global.\n' +
    '(function(){\nvar module = { exports: {} };\nvar exports = module.exports;\n' +
    cjs +
    '\nwindow.THREE = module.exports;\n})();\n');
} else {
  console.warn('[copy-shared] three not installed — 3D charts will fall back to flat rendering');
}

console.log('[copy-shared] vendor/ populated:', shared.join(', ') + ', supabase-config.js, three.js');
